name: phpstan

on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: phpstan-${{ github.ref }}
  cancel-in-progress: true

jobs:
  phpstan:
    name: phpstan
    runs-on: self-hosted

    strategy:
      matrix:
        php: ['8.4', "8.5"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Run PHPStan PHP v${{ matrix.php }}
        run: composer analyse -- --error-format=github
